### ISSUE TITLE
500 Internal Server Error on Test database connection

### ISSUE THREAD

**Issue by vaibhavmalushte** [gamonoid/icehrm#10]
Hi,

Downloaded latest version and trying to setup on my sub domain, while testing the database connectivity I got 500 internal server error in src/app/install/submit.php

I am not sure why I have to go to xxx.abcd.com/src to start installation, ideally it should be within document root, Also can you please explain if I install it like this, what will be my application URL? will it be xxx.abcd.com/src or xxx.abcd.com

Thank you

**Comment by thilinah** [comment]
Please download the release not the source. If you have downloaded the source you need to build it using phing or ant.

**Comment by vaibhavmalushte** [comment]
thanks thilinah and my bad did not read the docs :(
