### ISSUE TITLE
Placeholder Text in form field

### ISSUE THREAD

**Issue by apothik** [gamonoid/icehrm#101]
Hello
I have been trying to get this to work in the 'admin/employees/lib.js' where I can put a placeholder into the text field, but it doesn't display the data:

 [ "birthday", {"label":"Date of Birth","type":"text","placeholder":"YYYY-MM-DD","validation":""}],

Is this something I have to initialize somewhere else?

**Comment by thilinah** [comment]
From v21.1.0 placeholder attribute is supported
