### ISSUE TITLE
Does not run if webserver is not on default port 80

### ISSUE THREAD

**Issue by gansad** [gamonoid/icehrm#108]
Hi, seems like icehrm forces all url to the default port 80. How to make it run at other port i.e. if user trying to run the webserver with other port if the default port 80 is not available ? Somehow icehrm reloads to port 80.

**Comment by thilinah** [comment]
If you have changed the port after installation, you need to change URLs on icehrm/app/config.php to include the port.

**Comment by gansad** [comment]
Thanks for that.. Will try something like this now.
`if($_SERVER['SERVER_PORT'] != 80){

  define('BASE_URL', $_SERVER['SERVER_NAME'].":".$_SERVER['SERVER_PORT']);
  define('CLIENT_BASE_URL',BASE_URL.":".$_SERVER['SERVER_PORT']."/app/");
}
else {
  define('BASE_URL', $_SERVER['SERVER_NAME']);
  define('CLIENT_BASE_URL',BASE_URL."/app/");
}`
