### ISSUE TITLE
Vagrant issue 

### ISSUE THREAD

**Issue by sajjidakr** [gamonoid/icehrm#109]
Hi there ,

I have used Vagrant to load up my development environment. I followed the steps and the application is building fine. I now want to load the application. I can see the below instruction in the read me file but could not make sense of how to load icehrml from from. 

Navigate to to load icehrm from VM. (user:admin/pass:admin)

**Comment by thilinah** [comment]
Updated the read me file. You can access icehrm from http://clients.app.dev/dev
