### ISSUE TITLE
Time entries over two days

### ISSUE THREAD

**Issue by tjcasey** [gamonoid/icehrm#11]
How does an employee enter time for a shift that spans across two days?  eg.  Shift starts at 23:00 and ends the following morning at 07:00.

If they try to enter those times the following message appears "Start time should be less than End time".

Is there any way to do this without entering in 23:00-23:59 and then a second entry for 00:00-07:00?
![timeentry](https://cloud.githubusercontent.com/assets/16826223/13595816/814fe970-e562-11e5-94a2-8742b55af7cf.PNG)

**Comment by thilinah** [comment]
No. We do not want to implement this because it could affect our reports
