### ISSUE TITLE
Assist with Errors - API & Employee Deletion

### ISSUE THREAD

**Issue by sfrindel** [gamonoid/icehrm#110]
Any help would be greatly appreciated. Not sure if bugs or configuration errors.

os: centos 7.5
nginx: 1.12.2
php: 7.0.29 (& php-fpm)
icrhrm: v21.1

**Employee Deletion**: This is repeatable on the demo page - http://apps.gamonoid.com/icehrm-open/
--- Steps to reproduce: Terminate an Employee, Archive from "Temporarily Deactivated"
--- Description: No action is performed and php-fpm error log states : 
_26-Apr-2018 07:45:43 Asia/Colombo] PHP Fatal error:  Uncaught Error: Class 'Documents\Common\Model\EmployeeDocument' not found in /usr/share/nginx/html/employeefile/src/Employees/Admin/Api/EmployeesActionManager.php:119
Stack trace:
#0 /usr/share/nginx/html/employeefile/service.php(135): Employees\Admin\Api\EmployeesActionManager->deleteEmployee(Object(stdClass))
#1 /usr/share/nginx/html/employeefile/app/service.php(3): include('/usr/share/ngin...')
#2 {main}
  thrown in /usr/share/nginx/html/employeefile/src/Employees/Admin/Api/EmployeesActionManager.php on line 119_

**API**: still working on my config 
GET http://~ip address~/employeefile/rest.php?employees/(?page=1,limit=1)

_[26-Apr-2018 07:47:19 Asia/Colombo] PHP Fatal error:  Uncaught Error: Call to undefined function NewADOConnection() in /usr/share/nginx/html/employeefile/server.includes.inc.php:26
Stack trace:
#0 /usr/share/nginx/html/employeefile/rest.php(7): include()
#1 {main}
  thrown in /usr/share/nginx/html/employeefile/server.includes.inc.php on line 26_ 

GET http://~ip address~/employeefile/app/api/employees/(?page=1,limit=1)
- Error 404 13

nginx config:
```
server {
    listen       80;
    server_name  ~ip address~;
    root   /usr/share/nginx/html;
    index index.php index.html index.htm;
    location / {
        try_files $uri $uri/ =404;}
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;}
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        #fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_pass php-fpm;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;}
    location /employeefile/app/api/ {
        try_files $uri $uri/ /app/rest.php?/$uri&$args /employeefile/app/rest.php?/$uri&$args;}
}
```

**Comment by thilinah** [comment]
This is a known issue. We will fix this with next release

**Comment by thilinah** [comment]
Fixed in v23
