### ISSUE TITLE
v21.1.0.OS  has Installation issue on PHP 5.3 and PHP 5.4 

### ISSUE THREAD

**Issue by prbt2016** [gamonoid/icehrm#115]
Hi,
I tried to install ICEHRM  v21.1.0.OS on PHP 5.3 as well as PHP 5.4 .On PHP 5.3 i get this error: 

Array ( [type] => 4 [message] => syntax error, unexpected T_OBJECT_OPERATOR [file] => /{{path}}/{{to}}/{{icehrmdir}}/lib/composer/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php [line] => 15 ) 

and on PHP 5.4  i get this error : 

Array ( [type] => 64 [message] => Can't use function return value in write context [file] => /{{path}}/{{to}}/{{icehrmdir}}/src/Payroll/Admin/Api/PayrollActionManager.php [line] => 82 ) 
However script runs fine on PHP 5.5 .
This seems to be a PHP version compatibility issue.Are the PHP requirements changed ?
The site mentions PHP  requirement as 5.3 or higher

http://icehrm.github.io/docs/installation/ 

Could you please fix this issue or just raise the requirements on the website?.So that users wont face these problems

**Comment by thilinah** [comment]
We recommend php v5.6 or higher. We'll update the documentation

**Comment by prbt2016** [comment]
Thanks a lot for your prompt reply .
