### ISSUE TITLE
How to use API

### ISSUE THREAD

**Issue by dpnkrg** [gamonoid/icehrm#118]
i had download the open source version of icehrm and installed into my freehosting server account.
Website is working fine, but API not.

when i trying to access api it gives me 404 error.

How to use API for icehrm. 
Also please letme know, how to properly configure API for icehrm.

**Comment by thilinah** [comment]
I've updated the documentation for setting up rest API to be more descriptive. Please check and let me know if you are still having trouble setting it up.
https://thilinah.gitbooks.io/icehrm-guide/content/rest-api.html

**Comment by dpnkrg** [comment]
Hi thilinah, 

Thanks a lot for your reply. 

Now the API is working.

But how to solve this or properly configure this :

{
    "error": [
        [
            {
                "code": 401,
                "message": "Authorization bearer token not found or invalid"
            }
        ]
    ]
}

**Comment by thilinah** [comment]
The last section of the documentation explains how you can replace the bearer token with the token from your icehrm installation. You can use the token given in example requests

**Comment by dpnkrg** [comment]
tried but same error get.

can you share some example or reference link.

It will be very helpful for me.

**Comment by dpnkrg** [comment]
Solved the issue, by deploying project in root directory in server.

**Comment by consultitechguru** [comment]
I have downloaded the open-source version of icehrm and has installed into my hosting server account.
The website is working fine, but API does not work with the Mobile App??.

Can the API work in Open source and if yes how to do that?

**Comment by redesitos** [comment]
I have downloaded the open-source version of icehrm and has installed into my hosting server account.
The website is working fine, but API does not work with the Mobile App??.

Can the API work in Open source (apache) and if yes how to do that?
