### ISSUE TITLE
Leave approval not working v24.0.0.PRO

### ISSUE THREAD

**Issue by jcsa1986** [gamonoid/icehrm#135]
Good day.

We updated our app to the last version and now we are not able to approve the subordinate leaves. I am currently supervisor of some employees, they submit a leave request, I get notified (perfect), but when I go to the Subordinate Leave list, I don't get the gear icon to approve or reject. This happens no matter what role I set to my user:

![image1](https://user-images.githubusercontent.com/32680659/43289006-d98a4edc-90e6-11e8-8fac-818849344314.png)

If I use the superadmin user and go to Admin - Leave Settings - Employee Leave List, I get the gear icon, but don't get the options to approve or reject:

![image2](https://user-images.githubusercontent.com/32680659/43289007-d9a9e936-90e6-11e8-9ff5-fed4d8897aac.png)
![image3](https://user-images.githubusercontent.com/32680659/43289008-d9c49402-90e6-11e8-88b3-3f96ae8a7130.png)

Also, we don't seem to find any permission related to leave maanagement:

![image4](https://user-images.githubusercontent.com/32680659/43289009-d9e0661e-90e6-11e8-9511-201cfa684fd2.png)

I appreciate any help or guide with this issue.

Regards.

**Comment by gamonoid** [comment]
Fixed in v25.0
