### ISSUE TITLE
SMTP not Working - Use swiftmailer

### ISSUE THREAD

**Issue by bensonkb** [gamonoid/icehrm#14]
i have the similar issue as the url. 
https://bitbucket.org/thilina/icehrm-opensource/issues/12/smtp-issue-with-version-60
Not notification on smtp. But on PHP mailer the i receive the the following error. i follow the log .

[2016-03-24 13:04:11] HBS Hrm.INFO: Sending email to: byeujnysoyn@ttrrtt.grp/ from: HBS Hrm ticket@httrrtt.grp [] []
[2016-03-24 13:04:11] HBS Hrm.INFO: PHP mailer result :  [] []

I am not able to send mail.

**Comment by mumupoko** [comment]
i also experience the same, the smtp is not working

**Comment by thilinah** [comment]
Create a user. System will try to send an email. Then check icehrm/app/data/icehrm.log and icehrm/app/data/aap.log for fatal errors. If you are trying to connect to a working SMTP server. Also check if Net_SMTP module is installed.

**Comment by circuitmamu** [comment]
#18 please check @thilinah did you forgot to include the Net_SMTP file in project directory.

**Comment by circuitmamu** [comment]
@thilinah I think below PHPMailer class will be the best solution for PHP mail insted of NET_SMTP.
https://github.com/PHPMailer/PHPMailer

Because this class doesn't require to install any kind of module

**Comment by thilinah** [comment]
I'll keep this open till we add a new SMTP liberary

**Comment by thilinah** [comment]
Support swift mailer now https://github.com/gamonoid/icehrm/blob/dev/server.includes.inc.php
