### ISSUE TITLE
Installation Fail

### ISSUE THREAD

**Issue by Ron-Dave** [gamonoid/icehrm#144]
Trying to install iceHrm v24.0.0.OS
Here is my error Message:
Warning: include(C:/xampp/htdocs/icehrm/login.php): failed to open stream: No such file or directory in C:\xampp\htdocs\icehrm\app\login.php on line 3

Warning: include(): Failed opening 'C:/xampp/htdocs/icehrm/login.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\icehrm\app\login.php on line 3

[config.txt](https://github.com/gamonoid/icehrm/files/2589082/config.txt)

**Comment by mgchong** [comment]
I experienced the same issue on version icehrm-26.2.0.OS.

**Comment by mgchong** [comment]
Hi,

This works for me https://github.com/gamonoid/icehrm/issues/133

**Comment by thilinah** [comment]
Updated the manual installation instructions here: https://icehrm.gitbook.io/icehrm/part-1/manual-installation
