### ISSUE TITLE
Can't fresh install

### ISSUE THREAD

**Issue by woppywush** [gamonoid/icehrm#15]
version: icehrm_v16.0.OS
problem while checking database connectivity

(index):51 Uncaught TypeError: Cannot read property 'status' of null

**Comment by thilinah** [comment]
Please let me know your php version. This issue possibly fixed in v16.1

**Comment by luwum** [comment]
What is the  PHP version required to run v16.1

**Comment by thilinah** [comment]
We recommend having php v5.6 or above
