### ISSUE TITLE
Class '\Reports\Admin\Reports\EmployeeDetailsReport' not found

### ISSUE THREAD

**Issue by aidil90** [gamonoid/icehrm#162]
It seems like some of the classes are missing. can you clarify on that?

**Comment by thilinah** [comment]
This will be fixed in next release. For now, you can extract the attached into icehrm/core
[EmployeeDetailsReport.php.zip](https://github.com/gamonoid/icehrm/files/2747934/EmployeeDetailsReport.php.zip)
/src/Reports/Admin/Reports/

**Comment by aidil90** [comment]
thanks !
