### ISSUE TITLE
500 Internal Server Error - app/service.php

### ISSUE THREAD

**Issue by circuitmamu** [gamonoid/icehrm#17]
when we go to the Employees -> Documents section

this section is not loaded and when I check the log and firebug console I seen that app.service file is called 6 times and among 3 times it gives error beacuseof following.

PHP Fatal error:  Class 'Document' not found in D:\wamp\www\ice_hrm\esthrm161\classes\BaseService.php on line 675

PHP Fatal error:  Class 'EmployeeDocument' not found in D:\wamp\www\ice_hrm\esthrm161\classes\BaseService.php on line 86

**Comment by thilinah** [comment]
Issue is fixed in v18
