### ISSUE TITLE
Modify Employee Schema

### ISSUE THREAD

**Issue by williamhatcher** [gamonoid/icehrm#177]
I like IceHRM, however I'd like to use it for a nonstandard company; a company inside a game.
Due to the structure, I don't want -or need- to capture many of the required fields; email included. I would like to modify the employee requirements to capture just the in game name, discord name, and company related fields such as: Join & Termination Date, Department, Job title, and supervisor. Related; I'd like to remove the need for emails for the Users, if possible?

Is there a good way to go about doing this?

**Comment by stvogel** [comment]
Hi William,
I see you closed this issue. Did you find a way to make changes required fields to optional?
I would really be interested in your solution.

**Comment by stvogel** [comment]
Ok, found it out ;-)
Just to help others with the same question.
As the fields like e.g. nationality or marital_status are already NULLABLE in the database, only the frontend/form-fields have to be set to optional. 
This is done in web/admin/src/employees/lib.js where you can add the attribute 'allow-null': true.
After that don't forget to run gulp and redeploy web/dist.
