### ISSUE TITLE
NET_SMTP not found in the project

### ISSUE THREAD

**Issue by circuitmamu** [gamonoid/icehrm#18]
In lib\Mail\smtp.php on line 348 a file is included Net/SMTP.php but in whole project there is no class included anywhere so it gives error

include_once(Net/SMTP.php): failed to open stream: No such file or directory in D:\wamp\www\ice_hrm\esthrm161\lib\Mail\smtp.php on line 348

**Comment by gamonoid** [comment]
Please install https://pear.php.net/package/Net_SMTP/

On Wed, Jun 22, 2016 at 10:48 AM, circuitmamu <notifications@github.com>
wrote:

> In lib\Mail\smtp.php on line 348 a file is included Net/SMTP.php but in
> whole project there is no class included anywhere so it gives error
>
> include_once(Net/SMTP.php): failed to open stream: No such file or
> directory in D:\wamp\www\ice_hrm\esthrm161\lib\Mail\smtp.php on line 348
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gamonoid/icehrm/issues/18>, or mute the thread
> <https://github.com/notifications/unsubscribe/AOXf1ZPjClpAplw1iEhb49mZ-3rX84yKks5qOMWtgaJpZM4I7aeu>
> .
>



-- 
Thilina Hasantha
TP: +94 722 33 67 47
http://lk.linkedin.com/in/thilinah

**Comment by bensonkb** [comment]
I too have this issue.....

**Comment by circuitmamu** [comment]
I think PHPMailer will be best for mail class instead of this useless class

**Comment by thilinah** [comment]
Yes. We will switch to a different implementation
