### ISSUE TITLE
LDAP not working

### ISSUE THREAD

**Issue by mikespears** [gamonoid/icehrm#186]
I'm a new user of IceHRM, and am unable to get LDAP login working with my Active Directory setup. When attempting to login to IceHRM (added the user) I get "Login Failed". Attached is my LDAP config for IceHRM. 
![image](https://user-images.githubusercontent.com/24268035/57273773-0dfae680-7067-11e9-877e-c1ccafefed6d.png)

**Comment by exilepc** [comment]
I think your LDAP Manager DN is wrong, this is what I used on mine

<img width="598" alt="Screen Shot 2019-07-08 at 10 49 50 PM" src="https://user-images.githubusercontent.com/7470415/60862616-ec3aee80-a1d2-11e9-81ad-69bd24906aa7.png">

**Comment by mikespears** [comment]
Yea I ended up realizing a couple days later what I was doing wrong :D.. So much for writing LDAP DNs when half asleep :D

**Comment by alexnogard** [comment]
> 
> 
> Yea I ended up realizing a couple days later what I was doing wrong :D.. So much for writing LDAP DNs when half asleep :D

Hello Mike,
Can you share your resolution with us please ? 
Trying to connecte to my Active Directoy, but not working 

Thanks

**Comment by alexnogard** [comment]
> 
> 
> > Yea I ended up realizing a couple days later what I was doing wrong :D.. So much for writing LDAP DNs when half asleep :D
> 
> Hello Mike,
> Can you share your resolution with us please ?
> Trying to connecte to my Active Directoy, but not working
> 
> Thanks

All right, for the AD, the solution for me was : 

for the DN, do a query to the active directoy to have the full DN : 
dsquery user -name "username"

and put the correct user filter : samAccountName={}

Regards
