### ISSUE TITLE
Document upload in open source

### ISSUE THREAD

**Issue by nigyel** [gamonoid/icehrm#19]
Hello, I tried to explore the open source version but the Documents upload is not working. Is it disabled in open source version. I have installed it in my server also but its same there?
Thanks.

**Comment by nigyel** [comment]
Hello anyone here? Documents upload option/fields are not showing up in demo and open source version. Pls help.

**Comment by gcobantr** [comment]
I have the same problem! 
Can someone please help?

thx

**Comment by metallicgloss** [comment]
I am having the same issue, but I don't think anyone at ICE will actually assist, seeing as they want $500 a year for support. It would be great if they did, but, if you need documentation for employees at the minute, I'm going to have to move to a different open source software like Orange HRM as they actually support users.

**Comment by thilinah** [comment]
The documents module is not available for the open source version. Due to a bug the document tab was visible in previous version
