### ISSUE TITLE
your instalation doesn't work when fresh install

### ISSUE THREAD

**Issue by circuitmamu** [gamonoid/icehrm#2]
When I extracted the code from latest version to my domain

I open http://my-domain.com but it not works becasue your install code is in /src  directory

So I need to open http://my-domain.com/src

But I think as per my knowldge in previous 12.7 vesion of @thilinah main source in the root directory

So please please change this code asap an put main code in root direcoty becasue no one want the instalattion in the sub folder of domain.

**Comment by joeflack4** [comment]
Hello there and thanks for the download!

If you go ahead and check out the root directory of this repository, installation instructions should be up at the top of the readme that displays at the bottom of the page when you load the repository. The first step is to download a release, rather than source code directly. Here is a link for your convenience

https://github.com/gamonoid/icehrm/releases/latest 

I'm not sure why the code is organized in this fashion. Maybe Thilinah can comment. But I'm sure there is good reason. I hope that helps! If you get stuck on any other point of the installation, please consult those instructions. If you're still stuck, let us know and I will see if I can help.

**Comment by gamonoid** [comment]
The code is organized in that manner because it makes it easy for me to upgrade the platform used for icehrm. This is actually built on top of a platform we use to build other commercial applications and having this structure help me to upgrade the platform which is inside src folder easily.

If you want to install the application you should use the latest release. Also if you want to use the latest code then you can build the application using ant. There is a build.xml file available in root folder. Before running build, change following properties inside build.xml according to your environment.

```xml
<property name="toolsdir" value=""/>
 <property name="destination" value="${basedir}/build/app"/>
 <property name="origin" value="${basedir}/src"/>
 <property environment="env"/>
 <property name="env.appname" value="icehrm"/>
 <property name="env.Version" value="dev"/>
 <property name="installpath" value="/var/www/apps.gamonoid.com/icehrm-open-core"/>
```

**Comment by circuitmamu** [comment]
@joeflack4 @gamonoid @thilinah 

Can you please clarify me on a single point that how can I install your latest version with fresh install on main domain http://my-domain.com instead of open http://my-domain.com/src.

**Comment by joeflack4** [comment]
To install locally on your computer, you should be running server software. XAMPP would be an example. I would say it is a little bit easier to set up locally than on your domain via your webhost. But there are a few more steps.

*Setting up on your Domain*
1. Download the latest release. I recommend downloading "icehrm_v13.1.OS.zip" from: https://github.com/gamonoid/icehrm/releases/tag/v13.1.OS

FTP. You'll want to have FTP setup with your domain and use something like Filezilla. Unzip the release file. Then move it to the desired directory on your web server.

Database setup. Log in to your webhost. Follow the instructions here: https://github.com/gamonoid/icehrm/
You'll want to use phpMyAdmin or another MySQL setup method which you may find when you're logged into your webhost's control panel area. You'll need to do a few different things. (1) Create a database, such as "icehrmdb", (2) Create a *database user* such as "icehrmuser" and set a password for it, (3) Then you'll need to grant all permissions for your "icehrmdb" to "icehrmuser".

Installation. Navigate to the URL corresponding to the directory you installed IceHRM on your domain. If you installed a folder called "IceHRM" in your root directory, or public directory of your domain file structure, this will probably be something like: http://www.mydomain.com/icehrm
When you are there, you'll be greeted by an install page. Fill in the form according to how you set up the database and user in the previous step. If all works according to plan, the app will install and you'll be greeted with a log in.

Log in. Log in with your temporary credentials. Username: admin / Password: admin

Remove Install folder. You'll want to go into your file structure and delete or rename the 'app/install' subdirectory. You should now be good to go!

**Comment by circuitmamu** [comment]
@joeflack4 @gamonoid @thilinah 

1. Download the latest release. I recommend downloading "icehrm_v13.1.OS.zip" from: https://github.com/gamonoid/icehrm/releases/tag/v13.1.OS

as suggest by @joeflack4 but after download extract the file in to a folder which is inside icehrm-13.1.OS but you can manually download this file at your end and see that there is no index file present in the root directory it means it will not open the setup url. you have to navigate through /src directory forfully otherwise no installation work.

**Comment by thilinah** [comment]
Please download
https://github.com/gamonoid/icehrm/releases/download/v13.1.OS/icehrm_v13.1.OS.zip

Not the source code

On Wed, Oct 28, 2015 at 12:34 PM, circuitmamu <notifications@github.com>
wrote:

> @joeflack4 <https://github.com/joeflack4> @gamonoid
> <https://github.com/gamonoid> @thilinah <https://github.com/thilinah>
>
>    1. Download the latest release. I recommend downloading
>    "icehrm_v13.1.OS.zip" from:
>    https://github.com/gamonoid/icehrm/releases/tag/v13.1.OS
>
> as suggest by @joeflack4 <https://github.com/joeflack4> but after
> download extract the file in to a folder which is inside icehrm-13.1.OS but
> you can manually download this file at your end and see that there is no
> index file present in the root directory it means it will not open the
> setup url. you have to navigate through /src directory forfully otherwise
> no installation work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamonoid/icehrm/issues/2#issuecomment-151748261>.
>



-- 
Thilina Hasantha
TP: +94 722 33 67 47
http://lk.linkedin.com/in/thilinah

**Comment by circuitmamu** [comment]
@thilinah  @joeflack4  @gamonoid 
thanks for you response 

But as I seen some modules has been removed in this release and still many issues is repeated like unwanted zero at top when install, PHP short tags, database table name in capitalize manner.

I think those bugs need to be solved for make this app more proficient and easy to use for who use this app for first time.

**Comment by izeblood** [comment]
> @joeflack4 @gamonoid @thilinah
> 
> 1. Download the latest release. I recommend downloading "icehrm_v13.1.OS.zip" from: https://github.com/gamonoid/icehrm/releases/tag/v13.1.OS
> 
> as suggest by @joeflack4 but after download extract the file in to a folder which is inside icehrm-13.1.OS but you can manually download this file at your end and see that there is no index file present in the root directory it means it will not open the setup url. you have to navigate through /src directory forfully otherwise no installation work.

can you please make a video presentation about this issue in youtube to make it more clearly...please..

**Comment by izeblood** [comment]
> To install locally on your computer, you should be running server software. XAMPP would be an example. I would say it is a little bit easier to set up locally than on your domain via your webhost. But there are a few more steps.
> 
> _Setting up on your Domain_
> 
> 1. Download the latest release. I recommend downloading "icehrm_v13.1.OS.zip" from: https://github.com/gamonoid/icehrm/releases/tag/v13.1.OS
> 
> FTP. You'll want to have FTP setup with your domain and use something like Filezilla. Unzip the release file. Then move it to the desired directory on your web server.
> 
> Database setup. Log in to your webhost. Follow the instructions here: https://github.com/gamonoid/icehrm/
> You'll want to use phpMyAdmin or another MySQL setup method which you may find when you're logged into your webhost's control panel area. You'll need to do a few different things. (1) Create a database, such as "icehrmdb", (2) Create a _database user_ such as "icehrmuser" and set a password for it, (3) Then you'll need to grant all permissions for your "icehrmdb" to "icehrmuser".
> 
> Installation. Navigate to the URL corresponding to the directory you installed IceHRM on your domain. If you installed a folder called "IceHRM" in your root directory, or public directory of your domain file structure, this will probably be something like: http://www.mydomain.com/icehrm
> When you are there, you'll be greeted by an install page. Fill in the form according to how you set up the database and user in the previous step. If all works according to plan, the app will install and you'll be greeted with a log in.
> 
> Log in. Log in with your temporary credentials. Username: admin / Password: admin
> 
> Remove Install folder. You'll want to go into your file structure and delete or rename the 'app/install' subdirectory. You should now be good to go!

can you please make a video presentation about this issue in youtube to make it more clearly...please..
