### ISSUE TITLE
Not Login

### ISSUE THREAD

**Issue by Talha91** [gamonoid/icehrm#22]
how to solve this error please help login page not display
#21

**Comment by alex058** [comment]
write this the config.php file: 

`<?php 
ini_set('error_log', 'C:\xampp\apache\logs\icehrm.log');

define('CLIENT_NAME', 'app');
define('APP_BASE_PATH', 'c:\xampp\htdocs\icehrm\');
define('CLIENT_BASE_PATH', 'c:\xampp\htdocs\icehrm\app\');
define('BASE_URL','http://mycompany.com/icehrm/');
define('CLIENT_BASE_URL','http://mycompany.com/icehrm/app/');

define('APP_DB', 'icehrm_db');
define('APP_USERNAME', 'icehrm_user');
define('APP_PASSWORD', 'icehrm_user_pwd');
define('APP_HOST', 'localhost');
define('APP_CON_STR', 'mysql://'.APP_USERNAME.':'.APP_PASSWORD.'@'.APP_HOST.'/'.APP_DB);

//file upload
define('FILE_TYPES', 'jpg,png,jpeg');
define('MAX_FILE_SIZE_KB', 10 * 1024);`

**Comment by thilinah** [comment]
In windows you should use / in path instead of \, and you also need ending / in paths
e.g define('APP_BASE_PATH', 'c:/xampp/htdocs/icehrm/');
Check [](https://icehrm.com/docs/manual-installation)
