### ISSUE TITLE
Icehrm module error

### ISSUE THREAD

**Issue by stg1987** [gamonoid/icehrm#23]
the sections in the modules are not displaying in one shot. i've to refresh 2 times to get that section to display. So when i inspected the element...I'm getting this error in the console. 
**Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated.** 
I think its got to do with javascrpit file

![image](https://cloud.githubusercontent.com/assets/11308398/17695538/ab0bed30-63c6-11e6-8bee-a13316ee76a7.png)

**Comment by thilinah** [comment]
What is your chrome version and OS?

**Comment by stg1987** [comment]
OS is windows 10 and chrome version is '52.0.2743.116 m' which is the latest one.

**Comment by thilinah** [comment]
Fixed with v20, as we support installation from sources
