### ISSUE TITLE
Cant connect icehrm-prod on ipadress:8070

### ISSUE THREAD

**Issue by bsogulcan** [gamonoid/icehrm#245]
I'm trying to start with docker, its working on localhost:8070 but didnt getting any responce when i try with my local ip. Which configuration i have to change to run with my ip address.

**Comment by bsogulcan** [comment]
I can access without any problem when i installed manuel

**Comment by ayan013** [comment]
can you please explain how did you get response using your machine's IP. I am trying to run with my local IP but it showing "localhost refused to connect"..Please let me know how did you solve the issue.

**Comment by bsogulcan** [comment]
I just install LAMP Server and published with it and it works.
