### ISSUE TITLE
Application not launching

### ISSUE THREAD

**Issue by Jhide** [gamonoid/icehrm#25]
Hello,
I have installed the application on localhost using xampp but whenever I try to launch it, it keeps returning a object not found error
![ff](https://cloud.githubusercontent.com/assets/10080761/18083571/9ecf0f04-6e9b-11e6-8e58-c2bf51d2edb5.JPG)

**Comment by adamrifau** [comment]
i'm having same problem

**Comment by thilinah** [comment]
Fixed with v20, as we support installation from sources
