### ISSUE TITLE
Punch-in and Punch-out issue in Ice HRM Open source Platform

### ISSUE THREAD

**Issue by shammyes** [gamonoid/icehrm#260]
Dear Team,

Punch-in and Punch-out issue in Ice HRM Open source Platform

An employee can change Punch -in or Punch-out time and date .
![Screenshot 2021-06-28 224937](https://user-images.githubusercontent.com/86303882/123677767-25a71180-d863-11eb-8994-f850f606a854.jpg)

**Comment by melodiazz** [comment]
![image](https://user-images.githubusercontent.com/22655268/123726463-9af5ff00-d8c2-11eb-97d2-3edf1b5f4e87.png)
Login as admin, go to System-> Settings -> Attendance -> Attendance: Use Department Time Zone -> Set Value to Yes
