### ISSUE TITLE
Not populating Employee module with data

### ISSUE THREAD

**Issue by VegardGulbrandsen** [gamonoid/icehrm#27]
Hi
When adding info in the employee module, no data appear in the list. (This happens for all info in the employee module, Skills, Education etc.)  The employees are listed but it dont dispaly the info
![image 3](https://cloud.githubusercontent.com/assets/11646951/18264842/e2dfdaa8-7412-11e6-8365-f326ca15f186.jpg)

**Comment by thilinah** [comment]
Fixed with v20

**Comment by thilinah** [comment]
Fixed with v20
