### ISSUE TITLE
Search for languages spoken without having to enter an employee

### ISSUE THREAD

**Issue by lndnrm** [gamonoid/icehrm#272]
When looking to the employee section, searching for employees speaking a particular language, the filter asks for an employee to be chosen - which defies the idea of filtering for a language.

![image](https://user-images.githubusercontent.com/64414668/134636348-5e4ba0d4-eb18-4f0c-85ec-5381160f19c9.png)

It would be great to either choose all employees (via asteriks for example) or to drop the employee filter here.

**Comment by roshelrao** [comment]
Now you can filter languages without selecting an employee.
