### ISSUE TITLE
Filter for skill needs employee to be chosen

### ISSUE THREAD

**Issue by lndnrm** [gamonoid/icehrm#273]
When looking to the employee section, searching for employees having a particular skill, the filter asks for an employee to be chosen - which defies the idea of filtering for a skill.

![image](https://user-images.githubusercontent.com/64414668/134636967-e92f92df-07b5-42a6-8b3c-b393f4f66980.png)

It would be great to either choose all employees (via asteriks for example) or to drop the employee filter here.

**Comment by gamonoid** [comment]
Fixed with v31
