### ISSUE TITLE
Recruitment View

### ISSUE THREAD

**Issue by lndnrm** [gamonoid/icehrm#274]
After updating to the current version I found the recruitment view with all its data gone.
Is there any chance to get this back as we have been using this heavily for our GDPR save recruitment processes.

We'd be paying for a custom development here, too.

**Comment by ddave001** [comment]
Can you please contact, the IceHrmPro team via team@icehrm.com or through the contact form under http://icehrm.com, since recruitment is not an open-source module?

**Comment by lndnrm** [comment]
Sure,

I'm copying the whole trail. Actually, we are using the Pro Variant.

Michael Lindner

Am Fr., 24. Sept. 2021 um 09:51 Uhr schrieb ddave001 <
***@***.***>:
