### ISSUE TITLE
System\Field names setup all fields are blank

### ISSUE THREAD

**Issue by namnh8x** [gamonoid/icehrm#28]
I installed icehrm version 18.0. After installing, when I went to System\Field names setup, all the fields there are blank, although those fields exist in the database.
![screenshot from 2016-09-07 11-06-21](https://cloud.githubusercontent.com/assets/2390766/18299449/240ca014-74eb-11e6-8264-4a9bb24ecf81.png)

**Comment by thilinah** [comment]
What is the server OS and which web server are you using. Also what is your php version and mysql version

**Comment by namnh8x** [comment]
My environment details:

OS: Lubuntu 4.4.0-28-generic
Web Server: Apache/2.4.20 (Ubuntu)
PHP version: 7.0.4-7ubuntu2.1
MySQL version: Ver 14.14 Distrib 5.7.12

I already tried another Lubuntu but it got the same result.

**Comment by VegardGulbrandsen** [comment]
Hi
I have the same problem. This also happens in the employee module. Tried mulitpe new installations on new servers, but still same problem. 
My enviromental details: 
OS: Ubuntu 16.04.1
Web Server: Apache/2.4.18 (Ubuntu)
PHP version: 7.0.10-2+deb.sury.ord~xential+1 (cli) ( NTS )
MySQL version: 5.7.13-0ubuntu0.16.04.2 - (Ubuntu)
![image 3](https://cloud.githubusercontent.com/assets/11646951/18380716/05b8aace-7679-11e6-87dc-b9ec3101a00d.png)

**Comment by abel-kc** [comment]
same, having the same problem under ubuntu 16 LTS, and php7

**Comment by abel-kc** [comment]
problem is gone after setting mysql mode to empty

**Comment by thilinah** [comment]
Fixed with v20
