### ISSUE TITLE
Leave Management Module is not Available After Softaculous Installation

### ISSUE THREAD

**Issue by neltik** [gamonoid/icehrm#282]
Hi

After installing icehrm v30.0.0.OS using Softaculous, I can't see leave management module. I could see other modules such as time management and travel management.

I've tried ticking System > Manage Modules > Leave Management System, but it does not save the setting. And I can't see leave management module as shown in the user manual.

Please help.
Thanks.

**Comment by melodiazz** [comment]
Are you using the paid version? Leave Management module only available in paid version of icehrm.

**Comment by ddave001** [comment]
The leave management is only available in [IceHrmPro](https://icehrm.com/purchase-icehrmpro).
