### ISSUE TITLE
Employee list does not work.

### ISSUE THREAD

**Issue by ChKaEs** [gamonoid/icehrm#286]
I manually installed and downgraded my php from 8.0 to 7.4 otherwise I could not even log in. The employee management screen is not working. I can add employees and it properly saves. There are currently 2 employees in the database. The Dashboard shows the count as 2 and the Staff Directory shows both employees, but the Employee screen just shows a spinning wheel and never shows the list of employees.

**Comment by ddave001** [comment]
Please check if you are seeing any errors on icehrm log (icehrm/app/data/icehrm.log)? Also check the JS console for any errors.

**Comment by ChKaEs** [comment]
The log has many errors, but I don't think all are related to this issue.
PHP Warning:  scandir(/icehrm_v30/core/../extensions/): failed to open dir: No such file or directory in /icehrm_v30/core/src/Classes/ExtensionManager.php on line 38
PHP Warning:  scandir(): (errno 2): No such file or directory in /icehrm_v30/core/src/Classes/ExtensionManager.php on line 38
PHP Warning:  Invalid argument supplied for foreach() in /icehrm_v30/core/src/Classes/ExtensionManager.php on line 46
PHP Notice:  Undefined index: ob in /icehrm_v30/core/data.php on line 24
PHP Notice:  Undefined index: sSearch in /icehrm_v30/core/data.php on line 25
PHP Notice:  Undefined index: sorting in /icehrm_v30/core/src/Classes/BaseService.php on line 244
PHP Notice:  Undefined index: iSortCol_0 in /icehrm_v30/core/src/Classes/BaseService.php on line 248
PHP Notice:  Undefined index:  in /icehrm_v30/core/src/Classes/BaseService.php on line 248
PHP Notice:  Undefined index: sSortDir_0 in /icehrm_v30/core/src/Classes/BaseService.php on line 250
ICE.DEBUG: (client=app) Data Load Query (x1):1=1employee = ? LIMIT 0, 10 [] []
ICE.DEBUG: (client=app) Data Load Query Data (x1):["1"] [] []
ICE.DEBUG: (client=app) Get Data Error: [] []
ICE.DEBUG: (client=app) Data Load Query:1=1 LIMIT 0, 10 [] []
ICE.DEBUG: (client=app) Data Load Query Data:["1"] [] []
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /icehrm_v30/core/src/Classes/BaseService.php on line 665

The console gave a 403 error:

**Comment by ChKaEs** [comment]
The issue was Godaddy blocking the ajax request. The admin-bundle.js was returning a 403 error. I whitelisted my IP and it now works; however, that is not a permanent solution because at some point I will want to have other people logging in, so I guess I will need to allow public to that URL. For testing purposes I will leave it open to only my IP.
