### ISSUE TITLE
there is no database class folder or file inside v13.1.OS

### ISSUE THREAD

**Issue by circuitmamu** [gamonoid/icehrm#3]
I just download you latest relase 
https://github.com/gamonoid/icehrm/releases/tag/v13.1.OS

and check the all directory and files in github
https://github.com/gamonoid/icehrm/tree/v13.1.OS

but I'm unable to find the database class or folder inside this relase version

**Comment by joeflack4** [comment]
Hello Circuitmamu,

Are you trying to set up your database? If so, this does not require you to locate any sort of file.

Or are you just looking for this because you are looking to alter the program or understand it?

**Comment by circuitmamu** [comment]
@joeflack4 

Thanks for your reply I understand your concern. I use this program since many previous version released by @thilinah in his repo.

It is very good app and very easy to understand for everyone.

But I think that few changes in the code will make this app very proficient and easy to use for all who use this app that is unprofessional.

Because we are professional developers and understand the PHP codes easily and modify if any error occurs.

**Comment by joeflack4** [comment]
Ah, I see. I was hoping it was database connectivity. That would be easy!

I haven't looked at the database logic for the app yet. I'll try and have a look soon, and let you know if I find anything that I feel would help.

**Comment by thilinah** [comment]
We use AdoDb
