### ISSUE TITLE
 "Uncaught mysqli_sql_exception: Table 'icehrm.systemdata' doesn't exist" error logged in log file after installation of icehrm using xampp

### ISSUE THREAD

**Issue by namanpatilps** [gamonoid/icehrm#325]
05-Jan-2023 12:51:02 Asia/Colombo] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'icehrm.systemdata' doesn't exist in C:\xampp2\htdocs\icehrm_v32.1.0.OS\core\src\MyORM\MySqlActiveRecord.php:163
Stack trace:
#0 C:\xampp2\htdocs\icehrm_v32.1.0.OS\core\src\MyORM\MySqlActiveRecord.php(163): mysqli->prepare('SELECT * FROM S...')
#1 C:\xampp2\htdocs\icehrm_v32.1.0.OS\core\src\Model\BaseModel.php(317): MyORM\MySqlActiveRecord->Load('name = ?', Array)
#2 C:\xampp2\htdocs\icehrm_v32.1.0.OS\core\src\Classes\BaseService.php(2030): Model\BaseModel->Load('name = ?', Array)
#3 C:\xampp2\htdocs\icehrm_v32.1.0.OS\core\src\Connection\Common\ConnectionService.php(98): Classes\BaseService->getSystemData('sysDataTime')
#4 C:\xampp2\htdocs\icehrm_v32.1.0.OS\core\src\Connection\Admin\Api\ConnectionAdminManager.php(14): Connection\Common\ConnectionService->dispatchInstallationRequest()
#5 C:\xampp2\htdocs\icehrm_v32.1.0.OS\core\server.includes.inc.php(150): Connection\Admin\Api\ConnectionAdminManager->initialize()
#6 C:\xampp2\htdocs\icehrm_v32.1.0.OS\core\login.php(5): include('C:\\xampp2\\htdoc...')
#7 C:\xampp2\htdocs\icehrm_v32.1.0.OS\app\login.php(3): include('C:\\xampp2\\htdoc...')
#8 {main}
  thrown in C:\xampp2\htdocs\icehrm_v32.1.0.OS\core\src\MyORM\MySqlActiveRecord.php on line 163

**Comment by ddave001** [comment]
This issue is fixed with v32.4.0. Earlier icehrm wasn't supporting mysql 8.0.32.
