### ISSUE TITLE
[bug report] Wrong URL validation in app/install/index.php that prevents installation if url is HTTPS.

### ISSUE THREAD

**Issue by SheriefAlaa** [gamonoid/icehrm#36]
Hi,

As I am installing icehrm I noticed that if my base url is in https the install() js function refuses to proceed with the installation and spits an "Invalid base url." alert().

The reason for this is the [if condition that searches the string ](https://github.com/gamonoid/icehrm/blob/5f5c23b9441f08f7e1a213052bd7973e96327421/src/app/install/index.php#L134)

Thanks.

**Comment by thilinah** [comment]
Fixed in v19.0.OS
