### ISSUE TITLE
Removed Field not reflected on the form

### ISSUE THREAD

**Issue by Mayesoo** [gamonoid/icehrm#38]
I removed some fields using Field Names Setup, but to my surprise, the removed fields are still appearing on the Add New for employees. I thought this feature is meant to remove fields from an Employee table, and the removed fields will have its corresponding field names(labels) removed from the form

**Comment by thilinah** [comment]
Is this in open source or cloud version?

**Comment by Mayesoo** [comment]
its in open source version 18.0

**Comment by thilinah** [comment]
Seems to be fixed in v19.0. Can you please check if this issue is there in http://apps.gamonoid.com/icehrm-open

**Comment by Mayesoo** [comment]
Its still there in v19.0

I deleted immigrationstatus field using Field Names Setup as you can see from the attachment, on the form the Immigration Status is still there(attached)
![immigrationstatus_deleted](https://cloud.githubusercontent.com/assets/23070242/21380602/193f7ee2-c75f-11e6-87ea-2c74c4217c17.jpg)
![deletedimmigration_status](https://cloud.githubusercontent.com/assets/23070242/21380622/33a15d78-c75f-11e6-8747-945782fcee4e.jpg)
