### ISSUE TITLE
cant access.

### ISSUE THREAD

**Issue by Yovito** [gamonoid/icehrm#39]
when i try to go :
localhost:/icehrm//src/app/login.php
i'm getting this error !!!
Notice: Constant HOME_LINK_ADMIN already defined in /var/www/html/icehrm/src/config.base.php on line 9

( ! ) Notice: Constant HOME_LINK_OTHERS already defined in /var/www/html/icehrm/src/config.base.php on line 10

FYI: i'm using php 7, mysql 14.14

**Comment by Yovito** [comment]
when i try to go :
localhost:/icehrm//src/app/login.php
i'm getting this error  !!! 
Notice: Constant HOME_LINK_ADMIN already defined in /var/www/html/icehrm/src/config.base.php on line 9

( ! ) Notice: Constant HOME_LINK_OTHERS already defined in /var/www/html/icehrm/src/config.base.php on line 10


FYI: i'm using php 7, mysql 14.14

**Comment by curiousNoob** [comment]
Anyone has found solution?

**Comment by alex058** [comment]
i have the same problem.

**Comment by thilinah** [comment]
This should have been because you were using source from master to deploy instead of a release. But now this is fixed. You can directly use latest master or dev branch to deploy
