### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by roelpaulo** [gamonoid/icehrm#44]
I was installing it and after the installation, I got Server Error 500. I opened the log file and it says module not found. Attached the log

[icehrm_log.txt](https://github.com/gamonoid/icehrm/files/961315/icehrm_log.txt)

**Comment by hafeez1042** [comment]
Same here

**Comment by Mayank-software** [comment]
Please go through this response , will solve yr problem  
https://bitbucket.org/thilina/icehrm-opensource/issues/256/blank-page-is-coming-after-instaltion

**Comment by roelpaulo** [comment]
Thanks for your comment @Mayank-software, unfortunately we moved to a different platform and software but I will try to test it on my localhost when I have the time on my home to see if that path is the culprit of my Error 500 before :)
