### ISSUE TITLE
Couldn't Install ice Hrm in Windows server 2012 R2

### ISSUE THREAD

**Issue by rprateek** [gamonoid/icehrm#45]
I followed all the steps including the manual installation but i don't get past the installation config page.

I have Tested database connectivity it is ok. ... and when I install it installs 107 tables in the database but nothing happens after that. If i manually open the hrm link then it shows me object not found error in http://192.168.1.150/icehrm/app/CLIENT_BASE_URLlogin.php

Please help ... I even tried manual installation but with no luck..

**Comment by thilinah** [comment]
This might help https://thilinah.gitbooks.io/icehrm-guide/content/manual-installation.html
