### ISSUE TITLE
Uncaught Error: Class 'User' not found in C:\xampp\htdocs\icehrm\src\login.php:60

### ISSUE THREAD

**Issue by Mayank-software** [gamonoid/icehrm#46]
Uncaught Error: Class 'User' not found in C:\xampp\htdocs\icehrm\src\login.php:60
Stack trace:
#0 C:\xampp\htdocs\icehrm\src\app\login.php(3): include()
#1 {main}
  thrown in C:\xampp\htdocs\icehrm\src\login.php on line 60

Asia/Colombo] Array
(
)

Asia/Colombo] Array
(
    [username] => EMP001
    [password] => EMP001
    [remember] => remember
)

**Comment by thilinah** [comment]
Hi,
Please use the release instead of using source directly. If you need to build from source follow instructions here: https://github.com/gamonoid/icehrm/blob/master/readme.md#preparing-development-vm

**Comment by Mayank-software** [comment]
Thanks for replay , I am using windows 8.1 for build and run

**Comment by Mayank-software** [comment]
I am not able run this source in windows system , I followed all steps as you suggest.  and  Class 'User' not found same error through , Please let me know how can i solve this. and User file is not found in source FYI..

Thanks is advance for support.

**Comment by Mayank-software** [comment]
Thanks Thilina Hasantha , Resolve my issue
