### ISSUE TITLE
Login php not working after install

### ISSUE THREAD

**Issue by daleirvine12** [gamonoid/icehrm#48]
After installing IceHRM it says installation complete; however when you direct to the Login page it says the following error:

This page isn’t working

website url is currently unable to handle this request.
HTTP ERROR 500

Can anyone help?

**Comment by rohitbharti275** [comment]
Hi,

Even I am facing the same issue as installation was complete and it redirected to login.php page but i get the same error as you

**Comment by thilinah** [comment]
Can you see any errors in logs under icehrm/app/data?

**Comment by RPQD** [comment]
If they are experiencing the same issue I am the error is.

> [02-Sep-2017 04:03:24 Asia/Colombo] PHP Fatal error:  Uncaught Error: Call to a member function SetFetchMode() on boolean in /path/to/icehrm/adodb512/adodb-active-record.inc.php:405
Stack trace:
#0 /path/to/icehrm/adodb512/adodb-active-record.inc.php(153): ADODB_Active_Record->UpdateActiveTable(false)
#1 /path/to/icehrm/classes/SettingsManager.php(28): ADODB_Active_Record->__construct()
#2 /path/to/icehrm/server.includes.inc.php(91): SettingsManager->getSetting('System: Do not ...')
#3 /path/to/icehrm/login.php(5): include('/path/to...')
#4 /path/to/icehrm/app/login.php(3): include('/path/to...')
#5 {main}
  thrown in /path/to/icehrm/adodb512/adodb-active-record.inc.php on line 405

**Comment by Ghost-Hat** [comment]
I'm having same issue after new install I get nothing displayed, by inspecting page it is empty html tags with server response 500

and data from log file 'icehrm/app/data/icehrm.log'

`[26-Sep-2017 01:58:25 Asia/Colombo] PHP Fatal error:  Uncaught Error: Call to a member function SetFetchMode() on boolean in /var/www/html/MY_HOST/MY_SUB_DOMAIN/lib/adodb512/adodb-active-record.inc.php:405
Stack trace:
#0 /var/www/html/MY_HOST/MY_SUB_DOMAIN/lib/adodb512/adodb-active-record.inc.php(153): ADODB_Active_Record->UpdateActiveTable(false)
#1 /var/www/html/MY_HOST/MY_SUB_DOMAIN/src/Classes/SettingsManager.php(35): ADODB_Active_Record->__construct()
#2 /var/www/html/MY_HOST/MY_SUB_DOMAIN/server.includes.inc.php(55): Classes\SettingsManager->getSetting('System: Do not ...')
#3 /var/www/html/MY_HOST/MY_SUB_DOMAIN/login.php(5): include('/var/www/html/a...')
#4 /var/www/html/MY_HOST/MY_SUB_DOMAIN/app/login.php(3): include('/var/www/html/a...')
#5 {main}
  thrown in /var/www/html/MY_HOST/MY_SUB_DOMAIN/lib/adodb512/adodb-active-record.inc.php on line 405`

**Comment by fdofdez** [comment]
Same problem here, the installation was successful, but the login page wont load. 

[29-Sep-2017 14:24:21 America/Chicago] isConfigFileExists 1
[29-Sep-2017 14:24:21 America/Chicago] configData 
[29-Sep-2017 14:24:21 America/Chicago] Number of tables:0
[29-Sep-2017 14:24:24 America/Chicago] isConfigFileExists 1
[29-Sep-2017 14:24:24 America/Chicago] configData 
[29-Sep-2017 14:24:24 America/Chicago] Number of tables:0

**Comment by qokorendy** [comment]
Same Problem, :(

**Comment by thilinah** [comment]
Could be related to https://github.com/gamonoid/icehrm/issues/80. Try changing db user password and then change the password in config.php also.

**Comment by thilinah** [comment]
Fixed in https://github.com/gamonoid/icehrm/tree/dev
