### ISSUE TITLE
New Employee / Edit Employee Save giving validation error for optional field

### ISSUE THREAD

**Issue by KoderKrishanu** [gamonoid/icehrm#49]
When I tried to create a new employee I got the error dialog saying `Incorrect date value: '' for column 'confirmation_date' at row 1` .

I opened the default employee details, clicked on edit, and tried save without any change, got same error.
<img width="988" alt="screen shot 2017-07-12 at 11 45 41 pm" src="https://user-images.githubusercontent.com/6442642/28133123-902eb138-675c-11e7-853f-4957c5f692e2.png">

**Comment by rohitbharti275** [comment]
Hi Krishna,

Did login.php worked for you after succcessful  installation because I am getting http error 500 and login.php page is not appearing. Can you please guide me if you have done it

**Comment by jmmaguigad** [comment]
@rohitbharti275 you need to check the log file at app/data to see what error produced that http error 500.

**Comment by thilinah** [comment]
IceHrm still not fully tested with mysql strict mode. Removing strict mode would resolve your issue https://stackoverflow.com/questions/36374335/error-in-mysql-when-setting-default-value-for-date-or-datetime

**Comment by thilinah** [comment]
We fully support strict mode now. Also issue related to login 500 error was due to having special characters in password. This is fixed in dev branch (https://github.com/gamonoid/icehrm/tree/dev).

Will be released with next release.
