### ISSUE TITLE
icehrm installation

### ISSUE THREAD

**Issue by rohitbharti275** [gamonoid/icehrm#50]
Hi 

I have cloned the repository and followed all the instruction as specified and when i do http://apps-icehrm/icehrm/ in the browser it says site not found.

After cloning I have created a mysql database where in i have created a icehrm_db and icehrm_user grant all the permissions of icehrm_db to icehrm_user after that i have ran all the 2 scripts/icehrmdb.sql, scripts/icehrm_master_data.sql modified the contents of config.php in /var/www/apps-icehrm/icehrm/core-ext/app/config.php. please find the folder i have zipped after setting up config.php.
Please find the folder I have zipped i have cloned this code under /var/www/apps-icehrm/icehrm.
[icehrm.zip](https://github.com/gamonoid/icehrm/files/1148154/icehrm.zip)

**Comment by thilinah** [comment]
If you are going to use clone you need to build the project before moving to the web server (https://github.com/gamonoid/icehrm#setup-icehrm-development-environment)

If not you can download the latest release. If there were any issues with automated installation you may try the manual installation instructions https://thilinah.gitbooks.io/icehrm-guide/content/manual-installation.html
