### ISSUE TITLE
Migrating to IceHRM in August

### ISSUE THREAD

**Issue by zhzapgsb** [gamonoid/icehrm#51]
Suppose we start using icehrm on 1st August 2017. We have about 45 employees who have previously taken annual leaves, sick leaves etc since January. How do we reflect the previously taken leaves BEFORE we migrated to icehrm. 

I have taken a look at the Admin functionalities but couldnt find a way of doing that. Please advise. Thank you in advance.

**Comment by thilinah** [comment]
You can use the PTO feature to add negative leave balances for employees to reflect already taken leave https://thilinah.gitbooks.io/icehrm-guide/content/leavemanagement.html
