### ISSUE TITLE
Script unable to create some tables

### ISSUE THREAD

**Issue by atishagrawal** [gamonoid/icehrm#52]
The autoinstall script is unable to create tables like Employees, Users etc. because of the default values in date/timestamp.

**Comment by atishagrawal** [comment]
Even the table structure is wrong as per the inserted values, in icehrm_master_data.sql

**Comment by thilinah** [comment]
You may try disabling mysql strict mode () or try a manual installation https://thilinah.gitbooks.io/icehrm-guide/content/manual-installation.html

**Comment by thilinah** [comment]
Fully support strict mode now
