### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by kangramdan666** [gamonoid/icehrm#66]
here error messages:
Warning: include(c:\xampp\htdocs\icehrm2login.php): failed to open stream: No such file or directory in C:\xampp\htdocs\icehrm2\app\login.php on line 3

Warning: include(): Failed opening 'c:\xampp\htdocs\icehrm2login.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\icehrm2\app\login.php on line 3

and here is my config.php file:
<?php
ini_set('error_log', 'C:\xampp\apache\logs\icehrm.log');

define('CLIENT_NAME', 'app');
define('APP_BASE_PATH', 'c:\xampp\htdocs\icehrm2');
define('CLIENT_BASE_PATH', 'c:\xampp\htdocs\icehrm2\app');
define('BASE_URL','http://localhost/icehrm2/');
define('CLIENT_BASE_URL','http://localhost/icehrm2/app/');

define('APP_DB', 'icehrm');
define('APP_USERNAME', 'icehrm_user');
define('APP_PASSWORD', 'icehrm_pwd');
define('APP_HOST', 'localhost');
define('APP_CON_STR', 'mysql://'.APP_USERNAME.':'.APP_PASSWORD.'@'.APP_HOST.'/'.APP_DB);

//file upload
define('FILE_TYPES', 'jpg,png,jpeg');
define('MAX_FILE_SIZE_KB', 10 * 1024);

i have same error when try to install version 19 and 20

**Comment by thilinah** [comment]
Please note that BASE_PATH and APP_PATH both should have the ending \. Also in windows you should use / in paths instead of \.
e.g: 
```
define('APP_BASE_PATH', 'c:/xampp/htdocs/icehrm2/');
```

**Comment by kangramdan666** [comment]
thankyou, Its work
but I cant login into my icehrm
what is the default username & password?

**Comment by thilinah** [comment]
Please try admin/admin

**Comment by kangramdan666** [comment]
Im sorry, forget to import icehrm_master_data.sql
thankyou for your advise, lets explore IceHRM before real implementation begin

**Comment by alihaider663** [comment]
@thilinah CAn you please help with the same error. 
i am unable to resolve it please help

**Comment by liamka** [comment]
Not worked.

IceHrm v24.0.0.OS

**Comment by mgchong** [comment]
I experienced the same issue on version icehrm-26.2.0.OS.

https://github.com/gamonoid/icehrm/issues/144

**Comment by mgchong** [comment]
Hi All,

This works for me https://github.com/gamonoid/icehrm/issues/133

**Comment by karthick4055** [comment]
Hello All,

I'm also facing the same issue

[18-Jan-2024 08:51:11 Asia/Dubai] PHP Warning:  include(/var/www/icehrm/login.php): Failed to open stream: No such file or directory in /var/www/icehrm/app/login.php on line 3
[18-Jan-2024 08:51:11 Asia/Dubai] PHP Warning:  include(): Failed opening '/var/www/icehrm/login.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/icehrm/app/login.php on line 3

Please help to resolve this
