### ISSUE TITLE
Employee setup deleted fields still present

### ISSUE THREAD

**Issue by belizezooit** [gamonoid/icehrm#67]
Hello, I have been able to install ICEHrm Successfully.

Going through the employee setup, I have deleted The Nationality and
Ethnicity fields in the setup and still they are present when I go to add
an employee.

Please see the attachment.

Also, I accidentally added data to the Date of Termination Field and is
unable to delete the data.
![nationality and ethnicity removed from field names setup](https://user-images.githubusercontent.com/31997547/30496724-8e90e966-9a0d-11e7-96dc-d80fd5bc4662.jpg)
![remove nationality via system but still shows up in personal info](https://user-images.githubusercontent.com/31997547/30496726-8e936416-9a0d-11e7-8103-3d29042f7cbb.jpg)
![termination date cannot be removed once accidentally entered required filed canhed to not required](https://user-images.githubusercontent.com/31997547/30496725-8e917818-9a0d-11e7-8947-75b575101a52.jpg)
![nationality and ethnicity removed from field names setup](https://user-images.githubusercontent.com/31997547/30496746-9d594aba-9a0d-11e7-8a57-39dcfcf3986f.jpg)

**Comment by thilinah** [comment]
Issue regarding the termination date, which is a general issue where you can make a date field empty is a known issue and we will add a fix for this in next release. For the other two fields you should add those back into custom field list and set the display status to hidden as shown.

![screen shot 2017-09-15 at 8 45 05 pm](https://user-images.githubusercontent.com/1531403/30498424-f8d13f12-9a56-11e7-8f23-3a47308fa6f8.png)

Also as you have already deleted those two fields please execute following query in your db to add those back.

```
INSERT INTO `FieldNameMappings` (`type`, `name`, `textOrig`, `textMapped`, `display`) VALUES 
('Employee', 'nationality', 'Nationality', 'Nationality', 'Form'),
('Employee', 'ethnicity', 'Ethnicity', 'Ethnicity', 'Form');
```
