### ISSUE TITLE
PHP Fatal error:  Class 'Net_SMTP' not found

### ISSUE THREAD

**Issue by rezzsiddiqui** [gamonoid/icehrm#69]
Hi,

I just purchased the IceHRM pro couple of weeks back but the email module not seems to work. I checked the logs and found this error. PHP Fatal error:  Class 'Net_SMTP' not found in public_html/hrm/lib/Mail/smtp.php on line 349.

Can you guide me how to fix it? 

Thank you.

**Comment by thilinah** [comment]
Please install Net SMTP on your server http://pear.php.net/package/net_smtp

**Comment by rezzsiddiqui** [comment]
Hi,

We're using shared hosting from Godaddy. And I asked them about this module and they told me that they don't have this module available for shared hosting and that you can used php send mail for your email notification purposes. 

Can you please guide me about that? If that is really a possibility.

Thank you.

**Comment by thilinah** [comment]
Under settings module you can select PHP Mailer
