### ISSUE TITLE
DataTables warning issue

### ISSUE THREAD

**Issue by AbdelRahman-Elposhi** [gamonoid/icehrm#74]
Hi every one, 
I recently installed ICEHRM Cloud and I have an issue after importing my employees through th Data Import Files. Even after setting do not pass json to "YES". Still I see this error when I click on employee under admin.
DataTables warning (table id = 'grid'): DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error.
Please help.
![2017-10-01 2](https://user-images.githubusercontent.com/16709973/31059955-59e95068-a70a-11e7-9221-91441bf62663.png)

**Comment by thilinah** [comment]
Please send a support request to team@icehrm.com with your installation url
