### ISSUE TITLE
install icehrm error in Database is not empty

### ISSUE THREAD

**Issue by devatahir** [gamonoid/icehrm#75]
![capture](https://user-images.githubusercontent.com/31231849/31086781-6faef660-a7b8-11e7-9f93-150d28514bfe.PNG)
please solve the problem....

**Comment by thilinah** [comment]
Please check if you have any tables in db. If that's the case remove those or use a fresh db. Also you may try https://icehrm.com/docs/manual-installation

**Comment by kangramdan666** [comment]
remove all tables or database, its work for me
