### ISSUE TITLE
Can't login with LDAP after upgrade

### ISSUE THREAD

**Issue by jcsa1986** [gamonoid/icehrm#76]
Hello everybody!

We have just upgraded from v19.0 to v20.2 and we can´t login using our LDAP credentials. Are we missing something?

I bassically removed all files and folders from the installation directory except from the app folder and copy the new ones from the downloaded zip.

Please let me know if we have to provide more information about our installation.

Regards.

**Comment by thilinah** [comment]
Hi,
Are you using IceHrm Pro?

**Comment by jcsa1986** [comment]
Hi again.

I am going to change the question a bit.

We are very pleased with this software and came to the decision to purchase the Pro version.

How could we handle this?

If we purchase the software will we be able to upgrade our current installation without loosing any data?

Regards.

**Comment by thilinah** [comment]
Did you managed to resolve the LDAP issue?

You won't lose any data. If you are on v20.2 it's just a matter of replacing files. You can purchase icehrm pro directly from [https://icehrm.com/buy-icehrm-modules](https://icehrm.com/buy-icehrm-modules). If you have any questions about commercial products please send an email to team@icehrm.com

**Comment by jcsa1986** [comment]
Great, we will probably purchase the license this week.

Nope, we haven't been able to solve the issue. We had to rollback the version to 19.0 again.

Everything seems to be working fine when we do the upgrade, I'm able to login with admin account and the LDAP configuration is intact and enable. The logs don't show anything when the login fails. The weird thing is that the LDAP login works perfect with version 19.0.

Our system is on Centos 7 with MySQL database.

**Comment by thilinah** [comment]
This is fixed on master branch, you can replace the login.php file with following to get LDAP issue fixed 
https://github.com/gamonoid/icehrm/blob/master/login.php
