### ISSUE TITLE
Extraordinarily slow

### ISSUE THREAD

**Issue by krisgermann** [gamonoid/icehrm#77]
I've given PHP 4096M of space, yet it's still incredibly slow.

Debian 9.1 Stretch
PHP 7.0
Nginx (with FPM)

**Comment by thilinah** [comment]
You don't need that much of memory. You can do following to debug the issue:
1. Check logs for any errors (logs can be found inside icehrm/app/data)
2. Check db and version (even though it might work icehrm is not tested with maria db)
3. Check your browser network tab (chrome) to see which ajax calls taking time.
