### ISSUE TITLE
Import Employee data not available

### ISSUE THREAD

**Issue by anusuyab** [gamonoid/icehrm#78]
Import attendance and employee data is not available in Open source version. Is that for only hosted version ?

**Comment by ersten** [comment]
I have the same problem. I think there is something wrong with this data loader but I found nothing in logs or other places.

How we can fix it or find out what wrong with it?

**Comment by ersten** [comment]
I have solved the problem.
Just put files 'admin\data' from git to the install dir of your IceHRM.

https://github.com/gamonoid/icehrm/tree/master/admin/data

Hope this will help someone.

**Comment by anusuyab** [comment]
Yes.I did as you said. It's there. Thank you.
