### ISSUE TITLE
A database password rejected on installation

### ISSUE THREAD

**Issue by johngenza** [gamonoid/icehrm#80]
On installing, I had a database password like >Abc>*?1 with which I successfully managed to install icehrm but after that I could not login.  On inspecting the config.php in the /app/ folder I found that the password was being truncated to >Abc and that was causing errors. When I changed to a simpler password with only alphanumeric characters there was no problem logging in.

**Comment by thilinah** [comment]
This is a known issue and we will add a fix in a future release

**Comment by thilinah** [comment]
https://github.com/gamonoid/icehrm/commit/22f75d6e514327bd8842d29907083dfefbb9dd27
