### ISSUE TITLE
Several bugs I found which are severe.

### ISSUE THREAD

**Issue by tanmoy30** [gamonoid/icehrm#81]
Bugs are as follows:

1. Payroll report is not generating as it should. No addition and deduction are taking place. I did exactly as per your tutorial, but it is not working.
2. When an admin tries to modify any user's details, he should be able to do that just by clicking one the 'view' button (the magnifying glass icon) beside an employee name in 'Employees > Employees section. But, on clicking that button, the profile page of the logged in admin, opens. To edit an users profile, the admin has to log in as that user / employee and then he can edit the details of that user. But this should not be in this way.
3. When an employee got terminated, his name goes to 'Temporary Deactivated Employees' section, but that employee cannot be deleted permanently from there.

These are the three main issues which I have found so far.

**Comment by thilinah** [comment]
1. I'm not able to comment on this without being able to see your payroll configuration. Can you create a cloud installation for testing and add your payroll configuration there and share the url?

2. We will consider changing this

3. In "Temporary Deactivated Employees" there is a button to send the employee to "Terminated Employees" tab . That will delete the employee but still let you download employee data. Then under "Terminated Employees" tab you can permanently delete the employee

**Comment by tanmoy30** [comment]
Dear Thilina, my mom is in hospital. I apologize for this delay. Tomorrow I
will install and setup icehrm in a web server and will send you the link.
After that it will be up to you whether you will check it or not.

Regards.
