### ISSUE TITLE
413 Request Entity 

### ISSUE THREAD

**Issue by SergiusIII** [gamonoid/icehrm#82]
When I try to upload a document under employee document management I get the error "413 Request Entity" anyone got any ideas?

**Comment by thilinah** [comment]
Please check following:
https://www.cyberciti.biz/faq/linux-unix-apache-increase-php-upload-limit/
https://stackoverflow.com/questions/26717013/how-to-edit-nginx-conf-to-increase-file-size-upload

Even if you are using a different server, this is the reason for your issue
